language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

install:
  - "pip install -e .[testing]"
  - "pip install pytest-cov"
  - "pip install coveralls"

script: "pytest -v --cov=crank"

after_success:
  coveralls
